version: 0.2

env:
  variables:
    TF_VERSION: "1.8.0"
    AWS_ACCESS_KEY_ID:
    AWS_SECRET_ACCESS_KEY:
    AWS_SESSION_TOKEN:

   
phases:
  install:
    commands:
      - cd /usr/bin
      - curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - unzip -o terraform.zip
      - terraform --version

  build:
    commands:
      - cd ${CODEBUILD_SRC_DIR}/iaac/terraform/remote-state
      - terraform init -no-color

      - export AWS_ACCESS_KEY_ID
      - export AWS_SECRET_ACCESS_KEY
      - export AWS_SESSION_TOKEN

      - terraform apply -auto-approve

      - cd ..
      - terraform init -no-color
      - terraform apply -auto-approve
  post_build:
    commands:
      - echo "Terraform apply completed on `date`"

artifacts:
  files:
    - '**/*'
